define  ROOT C:\Program Files\nxlog

#define ROOT C:\Program Files (x86)\nxlog
#define ROOT C:\Program Files (x86)\nxlog

Moduledir  %ROOT%\modules
CacheDir  %ROOT%\data
Pidfile  %ROOT%\data\nxlog.pid
SpoolDir  %ROOT%\data
LogFile  %ROOT%\data\nxlog.log

<Extension _json>
  Module      xm_json
</Extension>

#Extension for MSSQL

<Extension mssql_csv>
  Module        xm_csv
  Fields        $Hostname, $SourceName, $Action_ID, $Result, $DataBase, $SV_Instace, $User, $Message
  FieldTypes    string, string, string, string, string, string, string, string
  Delimiter     ;
</Extension>

#Input for MSSQL

<Input in_mssql>
  Module       im_msvistalog
  SavePos	TRUE
  ReadFromLast	TRUE
  <QueryXML>
    <QueryList>
        <Query Id="0">
            <Select Path="Application">*</Select>
        </Query>
    </QueryList>
  </QueryXML>
  
# Finding some values:
# Replace white spaces
  Exec     $Message = $raw_event;
  Exec     if not ($SourceName =~ /"/MSSQL.*/ drop();
  Exec     if $raw_event =~ /action_id:(\S+)/ $Action_ID = $1;
  Exec     if $raw_event =~ /database_name:(\S+)/ $DataBase = $1;
  Exec     if $raw_event =~ /server_instance_name:(\S+)/ $SV_Instace = $1;
  Exec     if $raw_event =~ /session_server_principal_name:(\S+)/ $User = $1;
 
  <Exec>
    if $raw_event =~ /AUDIT_SUCCESS/
    {
    $Result = 'Success';
    }
    else
    $Result = 'Failure';
  </Exec>
  Exec     $Message = replace($Message, "\t", " "); $Message = replace($Message, "\n", " "); $Message = replace($Message, "\r", " ");
</Input>

#Output for MSSQL

<Output out_mssql>
  Module        om_tcp
  Host          10.51.100.8
  Port          11615
# Ensure we send in the proper format:
  Exec     $Hostname = hostname_fqdn();
  Exec     mssql_csv->to_csv(); $raw_event = $Hostname + ' mssql_logs: ' + $raw_event;
  Exec     to_json();
</Output>

#Route for MSSQL Logs

<Route mssql>
    Path in_mssql  => out_mssql
</Route>
